### ISSUE TITLE
Itemstack serializer do not serialize a color

### ISSUE THREAD

**Issue by Ravis96** [OkaeriPoland/okaeri-configs#35]
serdes-bukkit do not implement color from eg: LeatherArmorMeta.class.

**Comment by PinkLolicorn** [comment]
It's by design. This is also true for any other custom meta. ItemStackSerializer at the moment is relatively simple. For greatly improved compatibility, it is possible to enable a failsafe mode based on [ItemStackTransformer](https://github.com/OkaeriPoland/okaeri-configs/blob/b11c267a84acf4527281cda9560e292ac14afbeb/serdes-bukkit/src/main/java/eu/okaeri/configs/yaml/bukkit/serdes/transformer/ItemStackTransformer.java). Keep in mind, the mode is intended for persistence use and not human-readable configs.

```java
registry.register(new SerdesBukkit());
registry.registerExclusive(ItemStack.class, new ItemStackSerializer(true));
```

Custom MetaData support is tracked from now in #36.
